//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranty
    {
        public long ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string Email { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
        public string Description { get; set; }
        public Nullable<long> Admin_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
    }
}
